# Travis-CI Build for dynamitey 
# see travis-ci.org for details

language: csharp
solution: TestClient.sln

matrix:
  include:
    - dotnet:2.2
      mono: none
      os: osx
    - dotnet:2.2
      mono: none
      os: linux

script:
  - dotnet restore
