version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2-sdk

    working_directory: ~/repo

    steps:
       - checkout

       - run:
           name: Build
           command: |
              dotnet build --framework=netcoreapp2.0 TestClient.sln
           
